[package]
name = "advent_of_code_2020"
version = "0.1.0"
authors = ["Charles Giguère <charles.giguere.2@ens.etsmtl.ca>"]
edition = "2018"

[workspace]

[dependencies]
itertools = "0.10"
indoc = "1.0.3"
regex = "1.4.2"
serde_scan = "0.4.1"
rayon = "1.5.0"
aoc_helper = { git = "https://github.com/IceSentry/aoc_helper.git" }
